"use client";

import { useState, useEffect } from "react";

const CURRENCY_MAP: Record<string, { symbol: string; rate: number }> = {
  EUR: { symbol: "€", rate: 1 },
  USD: { symbol: "$", rate: 1.08 },
  GBP: { symbol: "£", rate: 0.86 },
  CAD: { symbol: "CA$", rate: 1.47 },
  AUD: { symbol: "AU$", rate: 1.65 },
  JPY: { symbol: "¥", rate: 163.5 },
  CHF: { symbol: "CHF", rate: 0.97 },
  SEK: { symbol: "kr", rate: 11.3 },
  NOK: { symbol: "kr", rate: 11.8 },
  DKK: { symbol: "kr", rate: 7.45 },
  PLN: { symbol: "zł", rate: 4.32 },
  CZK: { symbol: "Kč", rate: 24.8 },
  HUF: { symbol: "Ft", rate: 395 },
  RON: { symbol: "lei", rate: 4.97 },
  BGN: { symbol: "лв", rate: 1.96 },
  HRK: { symbol: "€", rate: 1 },
  TRY: { symbol: "₺", rate: 34.5 },
  BRL: { symbol: "R$", rate: 5.3 },
  MXN: { symbol: "MX$", rate: 18.4 },
  ARS: { symbol: "AR$", rate: 950 },
  INR: { symbol: "₹", rate: 90.2 },
  CNY: { symbol: "¥", rate: 7.85 },
  KRW: { symbol: "₩", rate: 1450 },
  SGD: { symbol: "S$", rate: 1.45 },
  HKD: { symbol: "HK$", rate: 8.45 },
  NZD: { symbol: "NZ$", rate: 1.78 },
  ZAR: { symbol: "R", rate: 19.8 },
  NGN: { symbol: "₦", rate: 1650 },
  EGP: { symbol: "E£", rate: 52.3 },
  AED: { symbol: "د.إ", rate: 3.97 },
  SAR: { symbol: "﷼", rate: 4.05 },
  QAR: { symbol: "﷼", rate: 3.93 },
  KWD: { symbol: "د.ك", rate: 0.33 },
  MYR: { symbol: "RM", rate: 5.05 },
  THB: { symbol: "฿", rate: 37.8 },
  PHP: { symbol: "₱", rate: 60.5 },
  IDR: { symbol: "Rp", rate: 16800 },
  VND: { symbol: "₫", rate: 27200 },
  RUB: { symbol: "₽", rate: 98 },
  UAH: { symbol: "₴", rate: 40.2 },
  ILS: { symbol: "₪", rate: 3.95 },
  KES: { symbol: "KSh", rate: 139 },
  GHS: { symbol: "GH₵", rate: 16.5 },
  TZS: { symbol: "TSh", rate: 2700 },
  MAD: { symbol: "MAD", rate: 10.8 },
  DZD: { symbol: "د.ج", rate: 146 },
  COP: { symbol: "COL$", rate: 4250 },
  PEN: { symbol: "S/", rate: 4.05 },
  CLP: { symbol: "CL$", rate: 1000 },
  PKR: { symbol: "₨", rate: 298 },
  BDT: { symbol: "৳", rate: 119 },
  LKR: { symbol: "Rs", rate: 328 },
  NPR: { symbol: "Rs", rate: 144 },
  MMK: { symbol: "K", rate: 2260 },
  KZT: { symbol: "₸", rate: 485 },
  UZS: { symbol: "сўм", rate: 13400 },
  GEL: { symbol: "₾", rate: 2.85 },
  AZN: { symbol: "₼", rate: 1.83 },
  AMD: { symbol: "֏", rate: 415 },
  MNT: { symbol: "₮", rate: 3650 },
  ISK: { symbol: "kr", rate: 148 },
  JMD: { symbol: "J$", rate: 167 },
  TTD: { symbol: "TT$", rate: 7.3 },
  BBD: { symbol: "Bds$", rate: 2.16 },
  GTQ: { symbol: "Q", rate: 7.8 },
  HNL: { symbol: "L", rate: 26.8 },
  NIO: { symbol: "C$", rate: 39.5 },
  PAB: { symbol: "B/.", rate: 1.08 },
  UYU: { symbol: "$U", rate: 43.5 },
  PYG: { symbol: "₲", rate: 7500 },
  BOB: { symbol: "Bs", rate: 7.45 },
  VES: { symbol: "Bs.S", rate: 36.5 },
  FJD: { symbol: "FJ$", rate: 2.45 },
  PGK: { symbol: "K", rate: 4.25 },
  WST: { symbol: "WS$", rate: 2.95 },
  TOP: { symbol: "T$", rate: 2.55 },
  SBD: { symbol: "SI$", rate: 8.75 },
  BND: { symbol: "B$", rate: 1.45 },
  MOP: { symbol: "MOP$", rate: 8.7 },
  KHR: { symbol: "៛", rate: 4350 },
  LAK: { symbol: "₭", rate: 21800 },
  BIF: { symbol: "FBu", rate: 3050 },
  RWF: { symbol: "RF", rate: 1400 },
  UGX: { symbol: "USh", rate: 4050 },
  ZMW: { symbol: "ZK", rate: 22.5 },
  MWK: { symbol: "MK", rate: 1740 },
  SZL: { symbol: "E$", rate: 19.8 },
  LSL: { symbol: "L", rate: 19.8 },
  NAD: { symbol: "N$", rate: 19.8 },
  MZN: { symbol: "MT", rate: 68.5 },
  AOA: { symbol: "Kz", rate: 895 },
  ETB: { symbol: "Br", rate: 61.5 },
  SDG: { symbol: "SDG", rate: 485 },
  SLL: { symbol: "Le", rate: 24000 },
  LRD: { symbol: "L$", rate: 215 },
  CVE: { symbol: "$", rate: 108 },
  STN: { symbol: "Db", rate: 24.5 },
  GMD: { symbol: "D", rate: 71 },
  GNF: { symbol: "FG", rate: 925 },
  LBP: { symbol: "L£", rate: 97500 },
  JOD: { symbol: "JD", rate: 0.77 },
  YER: { symbol: "﷼", rate: 270 },
  SYP: { symbol: "£", rate: 14000 },
  IQD: { symbol: "ع.د", rate: 1395 },
  AFN: { symbol: "؋", rate: 76 },
  MVR: { symbol: "Rf", rate: 16.6 },
  BTN: { symbol: "Nu.", rate: 90 },
  TWD: { symbol: "NT$", rate: 34.5 },
  CRC: { symbol: "₡", rate: 545 },
  DOP: { symbol: "RD$", rate: 63.5 },
  CUP: { symbol: "₱", rate: 25.7 },
  HTG: { symbol: "G", rate: 138 },
  BSD: { symbol: "B$", rate: 1.08 },
  KYD: { symbol: "CI$", rate: 0.9 },
  AWG: { symbol: "Afl", rate: 1.95 },
  BMD: { symbol: "$", rate: 1.08 },
  SVC: { symbol: "₡", rate: 9.45 },
  MRU: { symbol: "UM", rate: 42.5 },
};

const BASE_PRICE_EUR = 15.0;
const BASE_ORIGINAL_EUR = 29.95;

function getCountryFromTimezone(): string | null {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (!tz) return null;

    const TZ_COUNTRY: Record<string, string> = {
      "Europe/Paris": "FR",
      "Europe/Berlin": "DE",
      "Europe/London": "GB",
      "Europe/Madrid": "ES",
      "Europe/Rome": "IT",
      "Europe/Amsterdam": "NL",
      "Europe/Brussels": "BE",
      "Europe/Vienna": "AT",
      "Europe/Zurich": "CH",
      "Europe/Stockholm": "SE",
      "Europe/Copenhagen": "DK",
      "Europe/Oslo": "NO",
      "Europe/Helsinki": "FI",
      "Europe/Warsaw": "PL",
      "Europe/Prague": "CZ",
      "Europe/Budapest": "HU",
      "Europe/Bucharest": "RO",
      "Europe/Sofia": "BG",
      "Europe/Zagreb": "HR",
      "Europe/Athens": "GR",
      "Europe/Lisbon": "PT",
      "Europe/Dublin": "IE",
      "Europe/Tallinn": "EE",
      "Europe/Riga": "LV",
      "Europe/Vilnius": "LT",
      "Europe/Luxembourg": "LU",
      "Europe/Malta": "MT",
      "Europe/Bratislava": "SK",
      "Europe/Ljubljana": "SI",
      "Atlantic/Reykjavik": "IS",
      "America/New_York": "US",
      "America/Chicago": "US",
      "America/Denver": "US",
      "America/Los_Angeles": "US",
      "America/Anchorage": "US",
      "Pacific/Honolulu": "US",
      "America/Toronto": "CA",
      "America/Vancouver": "CA",
      "America/Edmonton": "CA",
      "America/Winnipeg": "CA",
      "America/Halifax": "CA",
      "America/Sao_Paulo": "BR",
      "America/Argentina/Buenos_Aires": "AR",
      "America/Mexico_City": "MX",
      "America/Bogota": "CO",
      "America/Lima": "PE",
      "America/Santiago": "CL",
      "America/Caracas": "VE",
      "America/Panama": "PA",
      "America/Costa_Rica": "CR",
      "America/Guatemala": "GT",
      "Asia/Tokyo": "JP",
      "Asia/Shanghai": "CN",
      "Asia/Hong_Kong": "HK",
      "Asia/Seoul": "KR",
      "Asia/Kolkata": "IN",
      "Asia/Calcutta": "IN",
      "Asia/Dubai": "AE",
      "Asia/Riyadh": "SA",
      "Asia/Qatar": "QA",
      "Asia/Kuwait": "KW",
      "Asia/Singapore": "SG",
      "Asia/Bangkok": "TH",
      "Asia/Ho_Chi_Minh": "VN",
      "Asia/Jakarta": "ID",
      "Asia/Kuala_Lumpur": "MY",
      "Asia/Manila": "PH",
      "Asia/Taipei": "TW",
      "Asia/Istanbul": "TR",
      "Asia/Tbilisi": "GE",
      "Asia/Baku": "AZ",
      "Asia/Tashkent": "UZ",
      "Asia/Almaty": "KZ",
      "Asia/Dhaka": "BD",
      "Asia/Karachi": "PK",
      "Asia/Colombo": "LK",
      "Asia/Kathmandu": "NP",
      "Asia/Yangon": "MM",
      "Asia/Phnom_Penh": "KH",
      "Asia/Vientiane": "LA",
      "Asia/Ulaanbaatar": "MN",
      "Asia/Tehran": "IR",
      "Asia/Baghdad": "IQ",
      "Asia/Jerusalem": "IL",
      "Asia/Beirut": "LB",
      "Asia/Amman": "JO",
      "Asia/Aden": "YE",
      "Asia/Damascus": "SY",
      "Africa/Cairo": "EG",
      "Africa/Lagos": "NG",
      "Africa/Nairobi": "KE",
      "Africa/Johannesburg": "ZA",
      "Africa/Casablanca": "MA",
      "Africa/Algiers": "DZ",
      "Africa/Tunis": "TN",
      "Africa/Accra": "GH",
      "Africa/Addis_Ababa": "ET",
      "Africa/Dar_es_Salaam": "TZ",
      "Africa/Kampala": "UG",
      "Africa/Kinshasa": "CD",
      "Africa/Lubumbashi": "CD",
      "Africa/Harare": "ZW",
      "Africa/Lusaka": "ZM",
      "Africa/Maputo": "MZ",
      "Africa/Windhoek": "NA",
      "Africa/Gaborone": "BW",
      "Africa/Maseru": "LS",
      "Africa/Mbabane": "SZ",
      "Africa/Kigali": "RW",
      "Africa/Bujumbura": "BI",
      "Africa/Khartoum": "SD",
      "Africa/Tripoli": "LY",
      "Australia/Sydney": "AU",
      "Australia/Melbourne": "AU",
      "Australia/Brisbane": "AU",
      "Australia/Perth": "AU",
      "Australia/Adelaide": "AU",
      "Pacific/Auckland": "NZ",
      "Pacific/Fiji": "FJ",
      "Pacific/Guam": "GU",
      "Pacific/Port_Moresby": "PG",
      "Pacific/Tongatapu": "TO",
      "Pacific/Apia": "WS",
      "America/Jamaica": "JM",
      "America/Port_of_Spain": "TT",
      "America/Barbados": "BB",
      "America/Guyana": "GY",
      "America/Paramaribo": "SR",
      "America/Cayenne": "GF",
      "America/Asuncion": "PY",
      "America/La_Paz": "BO",
      "America/Montevideo": "UY",
      "Asia/Kabul": "AF",
      "Europe/Chisinau": "MD",
      "Europe/Samara": "RU",
      "Europe/Minsk": "BY",
      "Europe/Kiev": "UA",
      "Europe/Kyiv": "UA",
      "Asia/Novosibirsk": "RU",
      "Asia/Vladivostok": "RU",
      "Asia/Yekaterinburg": "RU",
      "Asia/Krasnoyarsk": "RU",
      "Asia/Irkutsk": "RU",
      "Asia/Kamchatka": "RU",
      "Africa/Luanda": "AO",
      "Africa/Abidjan": "CI",
      "Africa/Dakar": "SN",
      "Africa/Bamako": "ML",
      "Africa/Niamey": "NE",
      "Africa/Ndjamena": "TD",
      "Africa/Bangui": "CF",
      "Africa/Malabo": "GQ",
      "Africa/Libreville": "GA",
      "Africa/Brazzaville": "CG",
      "Africa/Porto-Novo": "BJ",
      "Africa/Lome": "TG",
      "Africa/Ouagadougou": "BF",
      "Africa/Conakry": "GN",
      "Africa/Freetown": "SL",
      "Africa/Monrovia": "LR",
      "Africa/Bissau": "GW",
      "Africa/Praia": "CV",
      "Africa/Sao_Tome": "ST",
      "Indian/Maldives": "MV",
      "Indian/Mauritius": "MU",
      "Indian/Reunion": "RE",
    };

    return TZ_COUNTRY[tz] || null;
  } catch {
    return null;
  }
}

export function useCurrency() {
  const [currency, setCurrency] = useState<string>("EUR");

  useEffect(() => {
    const COUNTRY_CURRENCY: Record<string, string> = {
      US: "USD", GB: "GBP", CA: "CAD", AU: "AUD", JP: "JPY",
      CH: "CHF", SE: "SEK", NO: "NOK", DK: "DKK", PL: "PLN",
      CZ: "CZK", HU: "HUF", RO: "RON", BG: "BGN", HR: "HRK",
      TR: "TRY", BR: "BRL", MX: "MXN", AR: "ARS", IN: "INR",
      CN: "CNY", KR: "KRW", SG: "SGD", HK: "HKD", NZ: "NZD",
      ZA: "ZAR", NG: "NGN", EG: "EGP", AE: "AED", SA: "SAR",
      QA: "QAR", KW: "KWD", MY: "MYR", TH: "THB", PH: "PHP",
      ID: "IDR", VN: "VND", RU: "RUB", UA: "UAH", IL: "ILS",
      KE: "KES", GH: "GHS", TZ: "TZS", MA: "MAD", DZ: "DZD",
      CO: "COP", PE: "PEN", CL: "CLP", PK: "PKR", BD: "BDT",
      LK: "LKR", NP: "NPR", MM: "MMK", KZ: "KZT", UZ: "UZS",
      GE: "GEL", AZ: "AZN", AM: "AMD", MN: "MNT", IS: "ISK",
      JM: "JMD", TT: "TTD", BB: "BBD", GT: "GT", HN: "HN",
      NI: "NI", PA: "PA", UY: "UY", PY: "PY", BO: "BO",
      VE: "VE", FJ: "FJD", PG: "PGK", WS: "WS", TO: "TO",
      BN: "BND", KH: "KH", LA: "LA", MV: "MV", MU: "MU",
      IQ: "IQ", IR: "IR", JO: "JO", LB: "LB", YE: "YE",
      SY: "SY", TN: "TN", LY: "LY", SD: "SD", ET: "ET",
      RW: "RW", UG: "UG", CD: "CD", ZW: "ZW", ZM: "ZM",
      MZ: "MZ", NA: "NA", BW: "BW", LS: "LS", SZ: "SZ",
      BI: "BI", AO: "AO", CI: "CI", SN: "SN", ML: "ML",
      NE: "NE", TD: "TD", CF: "CF", GQ: "GQ", GA: "GA",
      CG: "CG", BJ: "BJ", TG: "TG", BF: "BF", GN: "GN",
      SL: "SL", LR: "LR", GW: "GW", CV: "CV", ST: "ST",
      AF: "AF", MD: "MD", BY: "BY",
    };

    const country = getCountryFromTimezone();
    if (country) {
      const cur = COUNTRY_CURRENCY[country];
      if (cur && CURRENCY_MAP[cur]) {
        setCurrency(cur);
      }
    }

    fetch("https://ipapi.co/json/")
      .then((r) => r.json())
      .then((data) => {
        if (data?.country_code) {
          const cur = COUNTRY_CURRENCY[data.country_code];
          if (cur && CURRENCY_MAP[cur]) {
            setCurrency(cur);
          }
        }
      })
      .catch(() => {});
  }, []);

  return currency;
}

export function formatPrice(baseEur: number, currency: string): string {
  const info = CURRENCY_MAP[currency];
  if (!info) return `€${baseEur.toFixed(2)}`;
  const converted = baseEur * info.rate;
  if (info.rate > 100) {
    return `${info.symbol}${Math.round(converted).toLocaleString()}`;
  }
  return `${info.symbol}${converted.toFixed(2)}`;
}

export function getConvertedPrice(baseEur: number, currency: string): number {
  const info = CURRENCY_MAP[currency];
  if (!info) return baseEur;
  return baseEur * info.rate;
}
